name: Automated MLOps Pipeline via GAS

on:
  repository_dispatch:
    types: [trigger_ml_pipeline] # Ini nama event yang bakal dipanggil sama GAS

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy requests lxml joblib tensorflow

      - name: Execute Pipeline Script
        run: python update_model.py

      - name: Commit and Push Updates
        run: |
          git config --global user.name "MLOps Robot"
          git config --global user.email "robot@elkana.mlops"
          git add HASIL_FINAL_TESIS_PASUT_*.csv
          git diff-index --quiet HEAD || git commit -m "🤖 [GAS Triggered] Proyeksi Masa Depan Diperbarui Parsial"
          git push